In [1]:
import numpy as np
import pandas as pd
from sklearn.neighbors import NearestNeighbors

In [2]:
df=pd.read_csv("./data/IoT_data_combined_filtered.csv")
iot_combined=df.drop(['Unnamed: 0', 'id', 'ts','Particles_higher_10um','Particles_higher_1um'], axis=1)
iot_combined=iot_combined.drop(['Particles_higher_0_5um','Particles_higher_2_5um','Particles_higher_5um','Pill Dispenser','PM_1','PM_10','PM_2_5','PMenv_2_5', 'Box', 'day'], axis=1)
iot_combined=iot_combined[['date','window','at_home','grassIndex','weedIndex','treeIndex','Particles_higher_0_3um','PMenv_10']]

dict={"window opened":1.0,"window closed":0.0, True:1.0, False:0.0}
iot_combined=iot_combined.replace({"window":dict, "at_home":dict})
iot_combined=iot_combined.fillna(0)

iot_combined

date  window  at_home  grassIndex  weedIndex  treeIndex  \
0     2022-05-12 07:55:45     1.0      1.0         0.0        0.0        0.0   
1     2022-05-12 07:55:56     1.0      1.0         0.0        0.0        0.0   
2     2022-05-12 07:56:07     0.0      1.0         0.0        0.0        0.0   
3     2022-05-12 07:56:14     1.0      1.0         0.0        0.0        0.0   
4     2022-05-12 07:56:32     1.0      1.0         0.0        0.0        0.0   
...                   ...     ...      ...         ...        ...        ...   
2540  2022-05-15 23:19:47     0.0      0.0         0.0        0.0        5.0   
2541  2022-05-15 23:29:47     0.0      0.0         0.0        0.0        5.0   
2542  2022-05-15 23:39:47     0.0      0.0         1.0        0.0        5.0   
2543  2022-05-15 23:49:47     0.0      0.0         1.0        0.0        5.0   
2544  2022-05-15 23:59:47     0.0      0.0         1.0        0.0        5.0   

      Particles_higher_0_3um  PMenv_10  
0                        0.0       0.0  
1                        0.0       0.0  
2                        0.0       0.0  
3                        0.0       0.0  
4                        0.0       0.0  
...                      ...       ...  
2540                 16906.0   49186.0  
2541                 16906.0   49186.0  
2542                 16906.0   49186.0  
2543                 16906.0   49186.0  
2544                 16906.0   49186.0  

[2545 rows x 8 columns]

In [5]:
scenario_vectors=pd.DataFrame()
scenario_vectors=scenario_vectors.append(scenario_dict,ignore_index=True)

## Add new saved scenario to the reference dataframe

In [ ]:
# scenario_date=input("Input the date of the push button as 'yyyy-mm-dd hh-mm-ss': \n")
# scenario_date

In [ ]:
# for index in iot_combined.index :
#     x_date=iot_combined.date[index]
#     if (scenario_date==x_date):
#         scenario_index=index
#         print(scenario_index)

In [31]:
scenario_index=input("Input the index of the scenario (testing only): \n")
scenario_index=int(scenario_index)
scenario_index

Input the index of the scenario (testing only): 
800


800

In [32]:
time=10 #how many past instances
scenario_df=iot_combined.loc[scenario_index-time:scenario_index]
scenario_dict={"Window": scenario_df["window"].values, "At home": scenario_df["at_home"].values,"Grass": scenario_df["grassIndex"].values,
              "Weed": scenario_df["weedIndex"].values,"Tree": scenario_df["treeIndex"].values,"Particles at home": scenario_df["PMenv_10"].values,
              "Scenario Index":scenario_index, "Scenario Date":scenario_df.date[scenario_index]}
scenario_dict


{'Window': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 'At home': array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 'Grass': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 'Weed': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 'Tree': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 'Particles at home': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 'Scenario Index': 800,
 'Scenario Date': '2022-05-12 13:25:50'}

In [33]:

if (np.all (scenario_index!=scenario_vectors["Scenario Index"])):
    scenario_vectors=scenario_vectors.append(scenario_dict,ignore_index=True)
scenario_vectors


At home  \
0  [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...   
1  [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...   
2  [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...   
3  [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...   
4  [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...   

                                               Grass  \
0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
1  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
2  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
3  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
4  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   

                                   Particles at home        Scenario Date  \
0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  2022-05-12 09:36:35   
1  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  2022-05-12 12:13:44   
2  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  2022-05-12 12:53:59   
3  [29218.0, 10139.0, 24695.0, 9824.0, 31328.0, 5...  2022-05-12 19:30:14   
4  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  2022-05-12 13:25:50   

   Scenario Index                                               Tree  \
0            36.0  [2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 0.0, ...   
1           564.0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
2           698.0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
3          2001.0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
4           800.0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   

                                                Weed  \
0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
1  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
2  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
3  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
4  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   

                                              Window  
0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
1  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
2  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
3  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
4  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...

## Compare similarity of current scenario to the "scenario_vectors" dataframe

In [16]:
from sklearn.metrics.pairwise import cosine_similarity,cosine_distances
from numpy import dot
from numpy.linalg import norm
from scipy import spatial

In [34]:
time=10 #how many past instances
current_scenario_df=iot_combined.loc[len(iot_combined)-11:len(iot_combined)-1]
current_scenario_dict={"Window": current_scenario_df["window"].values, "At home": current_scenario_df["at_home"].values,"Grass": current_scenario_df["grassIndex"].values,
              "Weed": current_scenario_df["weedIndex"].values,"Tree": current_scenario_df["treeIndex"].values,"Particles at home": current_scenario_df["PMenv_10"].values,
              "Scenario Date":current_scenario_df.date[len(iot_combined)-1]}
current_scenario_dict

{'Window': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 'At home': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 'Grass': array([1., 1., 0., 0., 0., 0., 0., 0., 1., 1., 1.]),
 'Weed': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 'Tree': array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]),
 'Particles at home': array([49186., 49186., 49186., 49186., 49186., 49186., 49186., 49186.,
        49186., 49186., 49186.]),
 'Scenario Date': '2022-05-15 23:59:47'}

In [35]:
current_scenario_vector=pd.DataFrame()
current_scenario_vector=current_scenario_vector.append(current_scenario_dict,ignore_index=True)
current_scenario_vector

At home  \
0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   

                                               Grass  \
0  [1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, ...   

                                   Particles at home        Scenario Date  \
0  [49186.0, 49186.0, 49186.0, 49186.0, 49186.0, ...  2022-05-15 23:59:47   

                                                Tree  \
0  [5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, ...   

                                                Weed  \
0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   

                                              Window  
0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...

### Grass Similarity

In [39]:
grass=scenario_vectors["Grass"]+1
grass=grass.to_list()
grass

[array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])]

In [40]:
results_grass=[]
current_grass=current_scenario_vector["Grass"][0]+1
current_grass=current_grass.tolist()
for i in grass:
    result = dot(current_grass, i.tolist())/(norm(current_grass)*norm(i.tolist()))
    results_grass+=[result]
    
results_grass

[0.9460998335825321,
 0.9460998335825321,
 0.9460998335825321,
 0.9460998335825321,
 0.9460998335825321]

In [41]:
resultsMeanGrass=sum(results_grass)/len(results_grass)
print("Current scenario similarity for GRASS INDEX: ", round(resultsMeanGrass, 2))

Current scenario similarity for GRASS INDEX:  0.95


### Tree Similarity

In [42]:
tree=scenario_vectors["Tree"]+1
tree=tree.to_list()
tree

[array([3., 3., 3., 3., 3., 3., 3., 3., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])]

In [43]:
results_tree=[]
current_tree=current_scenario_vector["Tree"][0]+1
current_tree=current_tree.tolist()
for i in tree:
    result = dot(current_tree, i.tolist())/(norm(current_tree)*norm(i.tolist()))
    results_tree+=[result]
    
results_tree

[0.9400193421607682, 1.0, 1.0, 1.0, 1.0]

In [44]:
resultsMeanTree=sum(results_tree)/len(results_tree)
print("Current scenario similarity for TREES INDEX: ", round(resultsMeanTree, 2))

Current scenario similarity for TREES INDEX:  0.99


### Weeds Similarity

In [45]:
weed=scenario_vectors["Weed"]+1
weed=weed.to_list()
weed

[array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])]

In [46]:
results_weed=[]
current_weed=current_scenario_vector["Weed"][0]+1
current_weed=current_weed.tolist()
for i in weed:
    result = dot(current_weed, i.tolist())/(norm(current_weed)*norm(i.tolist()))
    results_weed+=[result]
    
results_weed

[1.0, 1.0, 1.0, 1.0, 1.0]

In [47]:
resultsMeanWeed=sum(results_weed)/len(results_weed)
print("Current scenario similarity for WEEDS INDEX: ", round(resultsMeanWeed, 2))

Current scenario similarity for WEEDS INDEX:  1.0


### Particles Similarity

In [48]:
p=scenario_vectors["Particles at home"]+1
p=p.to_list()
p

[array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([29219., 10140., 24696.,  9825., 31329., 52892., 13527., 55964.,
        59804., 43932., 52380.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])]

In [49]:
results_p=[]
current_p=current_scenario_vector["Particles at home"][0]+1
current_p=current_p.tolist()
for i in p:
    result = dot(current_p, i.tolist())/(norm(current_p)*norm(i.tolist()))
    results_p+=[result]
    
results_p

[1.0, 1.0, 1.0, 0.8871313170938722, 1.0]

In [50]:
resultsMeanP=sum(results_p)/len(results_p)
print("Current scenario similarity for PARTICELS INDEX: ", round(resultsMeanP, 2))

Current scenario similarity for PARTICELS INDEX:  0.98


## Radar Plots

In [59]:
import plotly.express as px

df=pd.DataFrame( {
  'r':[resultsMeanGrass, resultsMeanTree,resultsMeanWeed,resultsMeanP],
  'theta':['Grass Index Similarity','Tree Index Similarity','Weed Index Similarity', 'Pollen Particles Similarity (at home)'],
})

fig = px.line_polar(df, r='r', theta='theta', line_close=True)

fig.update_traces(fill='toself')

fig.update_layout(
    polar = {
      "radialaxis_range" : [.9, 1],

    })

fig.show()

In [62]:
import plotly.express as px

df=pd.DataFrame( {
  'r':[.7, .93, .85, 1, .63, .55],
  'theta':['Grass Index Similarity','Tree Index Similarity','Weed Index Similarity', 'Pollen Particles Similarity (at home)', 'Weather', 'Precipitation'],
})

fig = px.line_polar(df, r='r', theta='theta', line_close=True)

fig.update_traces(fill='toself')

fig.update_layout(
    polar = {
      "radialaxis_range" : [.5, 1],

    })

fig.show()

In [64]:
import plotly.express as px

df=pd.DataFrame( {
  'r':[.7, .53, .57, .7, .63, .51],
  'theta':['Grass Index Similarity','Tree Index Similarity','Weed Index Similarity', 'Pollen Particles Similarity (at home)', 'Weather', 'Precipitation'],
})

fig = px.line_polar(df, r='r', theta='theta', line_close=True)

fig.update_traces(fill='toself')

fig.update_layout(
    polar = {
      "radialaxis_range" : [.5, 1],

    })

fig.show()

In [65]:
import plotly.express as px

df=pd.DataFrame( {
  'r':[.91, .93, 1, .95, .83, .75],
  'theta':['Grass Index Similarity','Tree Index Similarity','Weed Index Similarity', 'Pollen Particles Similarity (at home)', 'Weather', 'Precipitation'],
})

fig = px.line_polar(df, r='r', theta='theta', line_close=True)

fig.update_traces(fill='toself')

fig.update_layout(
    polar = {
      "radialaxis_range" : [.5, 1],

    })

fig.show()